services:
  main:
    build:
      context: .
      args:
        USERNAME: ${USER}
        UID: ${UID}
    runtime: nvidia
    volumes:
      - ${HOME}/.aws:${HOME}/.aws:ro
      - ${HOME}/.ssh:${HOME}/.ssh:ro
      - /opt/dvc/cache:/opt/dvc/cache
      - .:/ws
    environment:
      - WANDB_API_KEY=${WANDB_COMMON_API}
      - TOKENIZERS_PARALLELISM=true
      - WANDB_LOG_CONSOLE=off
    command: /bin/sh -c "while sleep 1000; do :; done"
