FROM tadejsv/ml-docker:eda

# Install pytorch
RUN  conda install pytorch torchvision torchtext cudatoolkit=10.2 -y -c pytorch-nightly && \
     conda install pytorch-lightning && \
     pip install transformers --no-cache-dir && \
     # Some cleanup
     conda clean -yaf && rm -rf /home/.cache