FROM ubuntu:20.04

ARG PYTHON_VERSION=3.8
ENV PATH /opt/conda/bin:$PATH

# For tzdata shit
ARG DEBIAN_FRONTEND=noninteractive

# Install all system stuff, including node
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
         build-essential \
         cmake \
         git \
         curl \
         ca-certificates \
         libjpeg-dev \
         libpng-dev && \
     curl -sL https://deb.nodesource.com/setup_14.x | bash -E - && \
     apt-get install nodejs -y --no-install-recommends && \
     rm -rf /var/lib/apt/lists/*

# Install all python stuff, including Pytorch and Pytorch Lightning
RUN curl -o ~/miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
     chmod +x ~/miniconda.sh && \
     ~/miniconda.sh -b -p /opt/conda && \
     rm ~/miniconda.sh && \
     conda config --system --prepend channels conda-forge && \
     conda install -y \ 
          python=$PYTHON_VERSION \
          pandas \ 
          mkl mkl-include \
          scipy \
          scikit-learn \
          matplotlib \
          jupyterlab \
          ipywidgets \
          widgetsnbextension && \
     conda install pytorch torchvision cudatoolkit=10.2 -y -c pytorch-nightly && \
     pip install https://github.com/PytorchLightning/pytorch-lightning/archive/master.zip --upgrade && \
     conda clean -yaf && \
     jupyter nbextension enable --py widgetsnbextension --sys-prefix && \
     jupyter labextension install @jupyter-widgets/jupyterlab-manager --no-build && \
     jupyter labextension install @jupyterlab/toc --no-build && \
     jupyter lab build && \
     npm cache clean --force 

# Open ports for Jupyter and Tensorboard
EXPOSE 8888 6006

# Transfer Jupyter settings and main script
ENV HOME /root
RUN jupyter notebook --generate-config
COPY jupyter_notebook_config.py $HOME/.jupyter/

# Setup file system
SHELL ["/bin/bash", "-c"]
RUN mkdir $HOME/project
WORKDIR $HOME/project

# Prepare entrypoint
ENV TINI_VERSION v0.19.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
COPY start-dev.sh /start-dev.sh
RUN chmod +x /start-dev.sh
RUN chmod +x /tini
ENTRYPOINT ["/tini", "-g", "--", "/start-dev.sh"]
